# This is a basic workflow to help you get started with Actions

name: Python script

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:  #Active to test/launch pithon script on command 

  schedule:
    - cron: '0 0/2 * * *' # At minute 0 past every 2 hours

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
      
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip pandas pip matplotlib pip plotly
          pip install pretty_html_table
                    
        # pip install -r requirements.txt
          
          


      # Runs a single command using the runners shell
      - name: Run my own Python script written by me
        env:
          MY_SECRET_TOKEN: ยง{{ secrets.MY_SECRET_TOKEN1 }}
        run: python update_fcr.py





      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
          
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_SECRET_TOKEN1 }}
          branch: main 
          
          
          
          
